import {useEffect,useMemo,useState} from 'react'
import type {APIClient} from '../../api/client'
import type {SchemaForeignKey,SchemaIndex,SchemaOperation,SchemaPreview,TableDetail} from '../../api/types'
import {Icon} from '../ui/Icon'
import {SelectControl} from '../ui/SelectControl'
import {diffColumns,type DraftColumn} from './schemaDraft'

type Section='fields'|'indexes'|'relations'|'permissions'|'ddl'
export function SchemaWorkspace({api,connectionId,schema,table,onBack,onSaved}:{api:APIClient;connectionId:string;schema:string;table:string;onBack:()=>void;onSaved:()=>void}){
 const [detail,setDetail]=useState<TableDetail|null>(null),[columns,setColumns]=useState<DraftColumn[]>([]),[section,setSection]=useState<Section>('fields'),[extra,setExtra]=useState<SchemaOperation[]>([]),[preview,setPreview]=useState<SchemaPreview|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const load=async()=>{setBusy(true);try{const d=await api.tableDetail(connectionId,schema,table);setDetail(d);setColumns(d.table.columns.map(x=>({...x,originalName:x.name})));setExtra([]);setPreview(null);setMessage('')}catch(e){setMessage(e instanceof Error?e.message:'无法加载表结构')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[connectionId,schema,table])
 const operations=useMemo(()=>detail?[...diffColumns(detail.table.columns,columns),...extra]:[],[detail,columns,extra])
 const change=(i:number,patch:Partial<DraftColumn>)=>setColumns(v=>v.map((x,n)=>n===i?{...x,...patch}:x))
 const makePreview=async()=>{setBusy(true);try{setPreview(await api.previewSchema(connectionId,schema,table,operations));setMessage('预览已生成，执行前会再次校验实时结构')}catch(e){setMessage(e instanceof Error?e.message:'DDL 预览失败')}finally{setBusy(false)}}
 const execute=async()=>{if(!preview)return;const dangerous=preview.risks.some(x=>x.level==='danger');if(dangerous&&!window.confirm(`包含危险操作：${preview.risks.map(x=>x.message).join('；')}。确认继续？`))return;setBusy(true);try{await api.executeSchema(connectionId,schema,table,preview.token,dangerous);setMessage('结构变更已保存');await load();onSaved()}catch(e){setMessage(e instanceof Error?e.message:'结构变更失败，草稿已保留')}finally{setBusy(false)}}
 if(!detail)return <div className="schema-loading">{busy?'正在读取表结构…':message}</div>
 return <section className="schema-workspace" aria-label="表结构编辑">
  <header className="schema-header"><button className="icon-button" aria-label="返回数据预览" onClick={onBack}><Icon name="chevron-left"/></button><div><h2>{schema}.{table}</h2><p>{detail.table.columns.length} 字段 · {detail.capabilities.transactionalDDL?'支持事务 DDL':'DDL 可能隐式提交'}</p></div><span className="schema-spacer"/>{operations.length>0&&<strong className="dirty-state">有 {operations.length} 项未保存修改</strong>}<button className="button" disabled={!operations.length||busy} onClick={makePreview}>预览 SQL</button><button className="button primary" disabled={!preview||busy} onClick={()=>void execute()}>保存修改</button></header>
  <nav className="schema-tabs">{([['fields','字段'],['indexes','索引'],['relations','关系'],['permissions','权限'],['ddl','DDL']] as [Section,string][]).map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</nav>
  <div className="schema-body">
   <div className="schema-main">
    {section==='fields'&&<><div className="schema-tools"><button className="button primary button-with-icon" onClick={()=>setColumns(v=>[...v,{name:`new_column_${v.length+1}`,type:'VARCHAR(255)',nullable:true,isNew:true}])}><Icon name="plus"/>新增字段</button></div><div className="fields-grid"><div className="field-row field-head"><span>#</span><span>字段名</span><span>数据类型</span><span>非空</span><span>默认值</span><span>注释</span><span>操作</span></div>{columns.map((c,i)=><div className="field-row" key={`${c.originalName||'new'}-${i}`}><span>{i+1}</span><input aria-label={`字段名 ${i+1}`} value={c.name} onChange={e=>change(i,{name:e.target.value})}/><input aria-label={`数据类型 ${i+1}`} value={c.type} onChange={e=>change(i,{type:e.target.value})}/><input aria-label={`非空 ${i+1}`} type="checkbox" checked={!c.nullable} onChange={e=>change(i,{nullable:!e.target.checked})}/><input aria-label={`默认值 ${i+1}`} value={c.default||''} onChange={e=>change(i,{default:e.target.value||undefined})}/><input aria-label={`注释 ${i+1}`} value={c.comment||''} onChange={e=>change(i,{comment:e.target.value})}/><button className="icon-button danger" aria-label={`删除字段 ${c.name}`} onClick={()=>setColumns(v=>v.filter((_,n)=>n!==i))}><Icon name="trash"/></button></div>)}</div></>}
    {section==='indexes'&&<IndexEditor indexes={detail.table.indexes||[]} onAdd={index=>setExtra(v=>[...v,{kind:'add_index',index}])} onDrop={name=>setExtra(v=>[...v,{kind:'drop_index',name}])}/>} 
    {section==='relations'&&<RelationEditor relations={detail.table.foreignKeys||[]} columns={columns.map(x=>x.name)} onAdd={foreignKey=>setExtra(v=>[...v,{kind:'add_foreign_key',foreignKey}])} onDrop={name=>setExtra(v=>[...v,{kind:'drop_foreign_key',name}])}/>} 
    {section==='permissions'&&<div className="schema-empty"><h3>权限（只读）</h3>{detail.permissions.length?detail.permissions.map(x=><code key={x}>{x}</code>):<p>当前连接未返回显式表权限。</p>}</div>}
    {section==='ddl'&&<pre className="ddl-source">{detail.ddl||'DDL 将在预览结构变更时生成。'}</pre>}
   </div>
   <aside className="ddl-panel"><h3>SQL 预览</h3>{preview?<><pre>{preview.statements.map(x=>x.sql+';').join('\n\n')}</pre>{preview.warnings?.map(x=><p className="ddl-warning" key={x}>{x}</p>)}{preview.risks.map(x=><p className={`ddl-risk ${x.level}`} key={x.kind+x.target}>{x.message}</p>)}</>:<p>修改字段、索引或关系后点击“预览 SQL”。</p>}</aside>
  </div><footer className="schema-status">{busy?'处理中…':message||'所有变更先预览，再执行'}</footer>
 </section>
}

function IndexEditor({indexes,onAdd,onDrop}:{indexes:SchemaIndex[];onAdd:(x:SchemaIndex)=>void;onDrop:(n:string)=>void}){const[name,setName]=useState(''),[cols,setCols]=useState(''),[unique,setUnique]=useState(false);return <div className="object-editor"><h3>索引</h3>{indexes.map(x=><div className="object-row" key={x.name}><strong>{x.name}</strong><span>{x.unique?'UNIQUE · ':''}{x.columns.join(', ')}</span><button className="button compact" onClick={()=>onDrop(x.name)}>删除</button></div>)}<div className="object-add"><input aria-label="索引名称" placeholder="索引名称" value={name} onChange={e=>setName(e.target.value)}/><input aria-label="索引字段" placeholder="字段，逗号分隔" value={cols} onChange={e=>setCols(e.target.value)}/><label><input type="checkbox" checked={unique} onChange={e=>setUnique(e.target.checked)}/> 唯一</label><button className="button primary" disabled={!name||!cols} onClick={()=>{onAdd({name,columns:cols.split(',').map(x=>x.trim()).filter(Boolean),unique});setName('');setCols('')}}>添加索引</button></div></div>}
function RelationEditor({relations,columns,onAdd,onDrop}:{relations:SchemaForeignKey[];columns:string[];onAdd:(x:SchemaForeignKey)=>void;onDrop:(n:string)=>void}){const[name,setName]=useState(''),[column,setColumn]=useState(columns[0]||''),[target,setTarget]=useState('public.table.id');return <div className="object-editor"><h3>外键关系</h3>{relations.map(x=><div className="object-row" key={x.name}><strong>{x.name}</strong><span>{x.columns.join(',')} → {x.refSchema}.{x.refTable}({x.refColumns.join(',')})</span><button className="button compact" onClick={()=>onDrop(x.name)}>删除</button></div>)}<div className="object-add"><input aria-label="外键名称" placeholder="外键名称" value={name} onChange={e=>setName(e.target.value)}/><SelectControl ariaLabel="本地字段" value={column} options={columns.map(x=>({value:x,label:x}))} onChange={setColumn}/><input aria-label="引用目标" placeholder="schema.table.column" value={target} onChange={e=>setTarget(e.target.value)}/><button className="button primary" disabled={!name||target.split('.').length!==3} onClick={()=>{const[s,t,c]=target.split('.');onAdd({name,columns:[column],refSchema:s,refTable:t,refColumns:[c],onDelete:'NO ACTION',onUpdate:'NO ACTION'});setName('')}}>添加关系</button></div></div>}
